name: QGC Plugins CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtcharts qtquick3d'

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Run Tests
      run: |
        cd build
        ctest -C Release --output-on-failure --verbose

    # - name: Build QGC Plugins
    #   run: ./build.bat

    # - name: Run Tests
    #   run: ./ci/test.bat

    - name: Package Artifacts
      run: |
        mkdir package
        copy build\plugins\*.dll package\
        copy build\bin\*.exe package\

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qgc-plugins-windows
        path: package/

  # build-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive

  #   - name: Install dependencies
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev cmake g++

  #   - name: Configure CMake
  #     run: |
  #       mkdir build
  #       cd build
  #       cmake ..

  #   - name: Build
  #     run: |
  #       cd build
  #       make -j$(nproc)

  #   - name: Test
  #     run: |
  #       cd build
  #       ctest --output-on-failure

  #   - name: Upload Artifacts
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: qgc-plugins-linux
  #       path: build/plugins/
